version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_modular
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --web.enable-lifecycle
    restart: unless-stopped

volumes:
  prometheus_data:
    driver: local
